#EC2 m5a.xlarge (4 instances)

apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-configs
  namespace: trino
data:
  node.properties: |-
    node.environment=production
    node.data-dir=/var/presto/data
  coordinator-jvm.config: |-
    -server
    -Xmx1G
    -Xms1G
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+UseGCOverheadLimit
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
  worker-jvm.config: |-
    -server
    -Xmx1G
    -Xms1G
    -XX:+UseG1GC
    -XX:G1HeapRegionSize=32M
    -XX:+UseGCOverheadLimit
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
    -Dcom.sun.management.jmxremote.rmi.port=9081
  coordinator-config.properties: |-
    coordinator=true
    node-scheduler.include-coordinator=false
    query.max-memory=85GB
    query.max-total-memory=117GB
    query.max-memory-per-node=6GB
    query.max-total-memory-per-node=9GB
    query-max-spill-per-node=50GB
    spill-enabled=true
    spiller-spill-path=/tmp/trino
    http-server.http.port=8080
    discovery-server.enabled=true
    jmx.rmiregistry.port=9080
    jmx.rmiserver.port=9081
    discovery.uri=http://trino-coordinator-service:8080

  worker-config.properties: |-
    coordinator=false
    http-server.http.port=8080
    query.max-memory=85GB
    query.max-total-memory=117GB
    query.max-memory-per-node=6GB
    query.max-total-memory-per-node=9GB
    query-max-spill-per-node=50GB
    spill-enabled=true
    spiller-spill-path=/tmp/trino
    jmx.rmiregistry.port=9080
    jmx.rmiserver.port=9081
    discovery.uri=http://trino-coordinator-service:8080