apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-worker
  namespace: ranger
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trino-worker
  template:
    metadata:
      labels:
        app: trino-worker
    spec:
      containers:
        - name: worker-node
          image: "pongthep/trino-k8s-worker:1.0.1"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "1Gi"
              cpu: "1500m"
            limits:
              memory: "1Gi"
              cpu: "1500m"