apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trino-pvc-claim
  namespace: ranger
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
